const ReactGlobal = React;

export default ReactGlobal;
export const Children = ReactGlobal.Children;
export const Fragment = ReactGlobal.Fragment;
export const cloneElement = ReactGlobal.cloneElement;
export const createContext = ReactGlobal.createContext;
export const createElement = ReactGlobal.createElement;
export const forwardRef = ReactGlobal.forwardRef;
export const isValidElement = ReactGlobal.isValidElement;
export const memo = ReactGlobal.memo;
export const useCallback = ReactGlobal.useCallback;
export const useContext = ReactGlobal.useContext;
export const useEffect = ReactGlobal.useEffect;
export const useId = ReactGlobal.useId;
export const useImperativeHandle = ReactGlobal.useImperativeHandle;
export const useLayoutEffect = ReactGlobal.useLayoutEffect;
export const useMemo = ReactGlobal.useMemo;
export const useReducer = ReactGlobal.useReducer;
export const useRef = ReactGlobal.useRef;
export const useState = ReactGlobal.useState;
